module.exports = {
  env: {
    METAMASK_ACCOUNT_MEMONIC:process.env.METAMASK_ACCOUNT_MEMONIC,
    RINKBEY_INFURA_NODE:process.env.RINKBEY_INFURA_NODE,
    DEPLOYED_CONTRACT_ADDRESS:process.env.DEPLOYED_CONTRACT_ADDRESS,
  }
}
